from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0, 600);")
Ruby = driver.find_element_by_css_selector("#text-22-sub_row_1-0-2-0-0>div>ul>li>a.woocommerce-LoopProduct-link")
Ruby.click()
Reviews = driver.find_element_by_xpath("//*[@id='product-160']/div[3]/ul/li[2]/a")
Reviews.click()
Five_star = driver.find_element_by_css_selector("#commentform>p.comment-form-rating>p>span>a.star-5")
Five_star.click()
Review_box = driver.find_element_by_id("comment")
Review_box.send_keys("Nice book!")
Name_box = driver.find_element_by_id("author")
Name_box.send_keys("Andrey")
Email_box = driver.find_element_by_id("email")
Email_box.send_keys("twek56@gmail.com")
Submit = driver.find_element_by_id("submit")
Submit.click()
driver.quit()