import time
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver

driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("https://practice.automationtesting.in/")
# My_acc = driver.find_element_by_css_selector("#menu-item-50 a")
# My_acc.click()
# Login = driver.find_element_by_id("username")
# Login.send_keys("twek56@gmail.com")
# Pass = driver.find_element_by_id("password")
# Pass.send_keys("asdASDasd123!@#")
# Login_btn = driver.find_element_by_name("login")
# Login_btn.click()
# # Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# # Shop.click()
# # HTML_5_forms = driver.find_element_by_xpath("//*[@id='content']/ul/li[3]/a[1]")
# # HTML_5_forms.click()
# # HTML_5_forms_HEADER = driver.find_element_by_css_selector(".product_title.entry-title")
# # HTML_5_HEADER_text = HTML_5_forms_HEADER.text
# # print("Текст заголовка -", HTML_5_HEADER_text)

# My_acc = driver.find_element_by_css_selector("#menu-item-50 a")
# My_acc.click()
# Login = driver.find_element_by_id("username")
# Login.send_keys("twek56@gmail.com")
# Pass = driver.find_element_by_id("password")
# Pass.send_keys("asdASDasd123!@#")
# Login_btn = driver.find_element_by_name("login")
# Login_btn.click()
# Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# Shop.click()
# cat_HTML = driver.find_element_by_css_selector(".cat-item-19 a")
# cat_HTML.click()
# items_count = driver.find_elements_by_class_name("product")
# if len(items_count) == 3:
#     print("На странице 3 товара")
# else:
#     print("Ошибка. Количество товаров на странице: " + str(len(items_count)))

# My_acc = driver.find_element_by_css_selector("#menu-item-50 a")
# My_acc.click()
# Login = driver.find_element_by_id("username")
# Login.send_keys("twek56@gmail.com")
# Pass = driver.find_element_by_id("password")
# Pass.send_keys("asdASDasd123!@#")
# Login_btn = driver.find_element_by_name("login")
# Login_btn.click()
# Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# Shop.click()
# Sorting = driver.find_element_by_css_selector("#content>form>select>option:nth-child(1)")
# Sorting_checked = Sorting.get_attribute("value")
# print(Sorting_checked)
# Order_by = driver.find_element_by_class_name("orderby")
# select_Order = Select(Order_by)
# select_Order.select_by_value("price-desc")
# Sorting_2 = driver.find_element_by_css_selector("#content > form > select > option:nth-child(6)")
# Sorting_2_checked = Sorting_2.get_attribute("value")
# print(Sorting_2_checked)

# My_acc = driver.find_element_by_css_selector("#menu-item-50 a")
# My_acc.click()
# Login = driver.find_element_by_id("username")
# Login.send_keys("twek56@gmail.com")
# Pass = driver.find_element_by_id("password")
# Pass.send_keys("asdASDasd123!@#")
# Login_btn = driver.find_element_by_name("login")
# Login_btn.click()
# Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# Shop.click()
# Android = driver.find_element_by_xpath("//*[@id='content']/ul/li[1]/a[1]/img")
# Android.click()
# Old_price = driver.find_element_by_css_selector(".price del .woocommerce-Price-amount")
# Old_price_text = Old_price.text
# assert "₹600.00" in Old_price_text
# New_price = driver.find_element_by_css_selector("div:nth-child(2)>p>ins>span")
# New_price_text = New_price.text
# assert "₹450.00" in New_price_text
# Image_opn = driver.find_element_by_css_selector("#product-169>div.images>a")
# Image_opn.click()
# Close = WebDriverWait(driver, 5).until_not(
#     EC.element_to_be_clickable((By.CLASS_NAME, "pp_close")))
# Close_btn = driver.find_element_by_class_name("pp_close")
# Close_btn.click()

# Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# Shop.click()
# Html_add = driver.find_element_by_xpath("//*[@id='content']/ul/li[4]/a[2]")
# Html_add.click()
# time.sleep(5)
# cart_check = driver.find_element_by_class_name("cartcontents")
# cart_check_text = cart_check.text
# print(cart_check_text, cart_check)
# assert cart_check_text == "1 Item"
# cart_price_check = driver.find_element_by_css_selector(".wpmenucart-contents > .amount")
# cart_price_check_text = cart_price_check.text
# assert "₹180.00" in cart_price_check_text
# cart = driver.find_element_by_class_name("wpmenucart-contents")
# cart.click()
# Subtotal = WebDriverWait(driver, 5).until_not(
#     EC.invisibility_of_element_located((By.CSS_SELECTOR, ".cart-subtotal .amount")))
# Total = WebDriverWait(driver, 5).until_not(
#     EC.invisibility_of_element_located((By.CSS_SELECTOR, ".order-total .amount")))

# Shop = driver.find_element_by_css_selector("#menu-item-40 > a")
# Shop.click()
# driver.execute_script("window.scrollBy(0, 300);")
# Html_add = driver.find_element_by_xpath("//*[@id='content']/ul/li[4]/a[2]")
# Html_add.click()
# time.sleep(1)
# JS_add = driver.find_element_by_xpath("//*[@id='content']/ul/li[5]/a[2]")
# JS_add.click()
# time.sleep(1)
# cart = driver.find_element_by_class_name("wpmenucart-contents")
# cart.click()
# time.sleep(5)
# remove = driver.find_element_by_css_selector("tr:nth-child(1)>td.product-remove>a")
# remove.click()
# Undo = driver.find_element_by_css_selector("div.woocommerce-message>a")
# Undo.click()
# Quantity = driver.find_element_by_css_selector("tr:nth-child(1)>td.product-quantity>div>input")
# Quantity.clear()
# Quantity.send_keys(3)
# Update_basket = driver.find_element_by_css_selector("tr:nth-child(3)>td>input.button")
# Update_basket.click()
# Quantity_check = driver.find_element_by_css_selector("tr:nth-child(1)>td.product-quantity>div>input")
# Quantity_checked = Quantity_check.get_attribute("value")
# print(Quantity_checked)
# time.sleep(5)
# Apply_coupon = driver.find_element_by_name("apply_coupon")
# Apply_coupon.click()
# Coupon_error = driver.find_element_by_css_selector("div.woocommerce>ul>li")
# Coupon_error_text = Coupon_error.text
# assert "Please enter a coupon code." in Coupon_error_text

Shop = driver.find_element_by_css_selector("#menu-item-40>a")
Shop.click()
driver.execute_script("window.scrollBy(0, 300);")
Html_add = driver.find_element_by_xpath("//*[@id='content']/ul/li[4]/a[2]")
Html_add.click()
time.sleep(1)
cart = driver.find_element_by_class_name("wpmenucart-contents")
cart.click()
time.sleep(5)
checkout = driver.find_element_by_class_name("checkout-button")
checkout.click()
time.sleep(5)
Name = driver.find_element_by_id("billing_first_name")
Name.send_keys("Andrey")
Last_name = driver.find_element_by_id("billing_last_name")
Last_name.send_keys("Ostanin")
Email = driver.find_element_by_id("billing_email")
Email.send_keys("twek56@gmail.com")
Phone = driver.find_element_by_id("billing_phone")
Phone.send_keys("9252525252")
Country = driver.find_element_by_id("select2-chosen-1")
Country.click()
Country_box = driver.find_element_by_id("s2id_autogen1_search")
Country_box.send_keys("Russia")
Country_btn = driver.find_element_by_id("select2-results-1")
Country_btn.click()
Address = driver.find_element_by_id("billing_address_1")
Address.send_keys("Prospect Lenina")
City = driver.find_element_by_id("billing_city")
City.send_keys("Nizhniy Tagil")
State = driver.find_element_by_id("billing_state")
State.send_keys("Sverdlovskaya oblast")
Postcode = driver.find_element_by_id("billing_postcode")
Postcode.send_keys("622049")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(5)
Check_payments = driver.find_element_by_id("payment_method_cheque")
Check_payments.click()
Place_order = driver.find_element_by_id("place_order")
Place_order.click()
Complete_order = WebDriverWait(driver, 10).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "div.woocommerce>p.woocommerce-thankyou-order-received"),
                                     "Thank you. Your order has been received."))
Complete_order2 = WebDriverWait(driver, 10).until(
    EC.text_to_be_present_in_element((By.CSS_SELECTOR, "div.woocommerce>ul>li.method>strong"),
                                     "Check Payments"))
driver.quit()
